import React, { useState, useEffect } from 'react';
import { 
  ChevronLeft, Shield, CheckCircle2, AlertTriangle, FileSearch, 
  ArrowUpRight, Download, Share2, ShieldCheck, ChevronRight, 
  Info, Zap, BarChart3, Bookmark, X, Brain
} from 'lucide-react';
import toast from 'react-hot-toast';
import { generateChatResponse } from '../../../services/geminiService';
import { apiService } from '../../../services/apiService';

const defaultCompliance = {
  score: 82,
  riskLevel: 'Medium',
  lastAudit: new Date().toLocaleDateString(),
  alerts: [
    { id: '1', title: 'Update Privacy Policy', desc: 'Privacy Policy missing GDPR & DPDP explicit consent frameworks.', date: 'Today', priority: 'High' },
    { id: '2', title: 'Section 65B Missing', desc: 'Uploaded electronic records do not have signed Section 65B admissibility certificates.', date: 'Yesterday', priority: 'High' },
    { id: '3', title: 'Enterprise SLA Liabilities', desc: 'Enterprise SLA contains liability caps that conflict with municipal consumer court rules.', date: '3 days ago', priority: 'Medium' }
  ],
  requirements: [
    { id: 'req1', title: 'DPDP Act Compliance Alignment', score: 95, status: 'Compliant' },
    { id: 'req2', title: 'Section 65B Electronic Proofs', score: 40, status: 'Warning' },
    { id: 'req3', title: 'NDAs & Confidentiality Audits', score: 85, status: 'Compliant' },
    { id: 'req4', title: 'BNS Criminal Code Compliances', score: 90, status: 'Compliant' },
    { id: 'req5', title: 'ISO 27001 Security Controls', score: 78, status: 'Warning' }
  ]
};

const ComplianceCenter = ({ currentCase, onBack, theme, onUpdateCase }) => {
  const isDark = theme === 'dark';
  const [stats, setStats] = useState(null);
  const [alerts, setAlerts] = useState([]);
  const [requirements, setRequirements] = useState([]);
  const [loading, setLoading] = useState(true);

  // AI Modal for auditing individual compliance items
  const [auditItem, setAuditItem] = useState(null);
  const [auditResponse, setAuditResponse] = useState('');
  const [isAuditing, setIsAuditing] = useState(false);

  useEffect(() => {
    loadComplianceData();
  }, [currentCase]);

  const loadComplianceData = () => {
    setLoading(true);
    try {
      let data = (currentCase && currentCase.compliance) ? currentCase.compliance : defaultCompliance;
      
      const total = data.requirements.reduce((sum, r) => sum + r.score, 0);
      const score = Math.round(total / data.requirements.length);
      
      const updatedStats = {
        score: score,
        pending: data.alerts.length,
        lastAudit: data.lastAudit || new Date().toLocaleDateString(),
        riskLevel: score > 90 ? 'Low' : (score > 70 ? 'Medium' : 'High')
      };
      
      setStats(updatedStats);
      setAlerts(data.alerts);
      setRequirements(data.requirements);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  const handleExportReport = () => {
    if (!stats) return;
    
    const reportContent = `
AISA ENTERPRISE COMPLIANCE REPORT
==================================
Compliance Score: ${stats.score}%
Risk Level: ${stats.riskLevel}
Last Audit Date: ${stats.lastAudit}
Pending Alerts: ${stats.pending}

Current Pending Issues:
${alerts.map(a => `- [${a.priority}] ${a.title}: ${a.desc} (${a.date})`).join('\n')}

Requirements Tracker Summary:
${requirements.map(r => `- ${r.title}: ${r.score}% [${r.status}]`).join('\n')}

Generated by AISA Legal AI.
`;

    if (navigator.share) {
      navigator.share({
        title: 'Compliance Report',
        text: reportContent
      }).catch(err => console.log(err));
    } else {
      navigator.clipboard.writeText(reportContent);
      toast.success("Compliance report summary copied to clipboard!");
    }
  };

  const handleReviewFix = async (item) => {
    setAuditItem(item);
    setAuditResponse('');
    setIsAuditing(true);

    try {
      const prompt = `Perform a rapid compliance audit for the following issue:
      Title: ${item.title}
      Description: ${item.desc}
      Priority: ${item.priority}
      
      Provide:
      1. Legal exposure analysis
      2. Step-by-step resolution plan
      3. Recommended wording/clauses to insert to resolve the conflict.`;

      const systemPrompt = `You are the AISA Enterprise Compliance Auditor. Provide short, structured, actionable advice. Output in clean Markdown.`;
      
      const response = await generateChatResponse([], prompt, systemPrompt, [], 'English', null, 'legal');
      const text = response.reply || response || '';
      setAuditResponse(text);
    } catch (e) {
      toast.error("Failed to run compliance auditor.");
    } finally {
      setIsAuditing(false);
    }
  };

  const toggleRequirement = async (reqId) => {
    if (!currentCase?._id) {
      toast.error("An active case is required to save updates.");
      return;
    }
    try {
      let data = currentCase.compliance || defaultCompliance;
      const updatedRequirements = data.requirements.map(r => {
        if (r.id === reqId) {
          const isCompliant = r.status === 'Compliant';
          return {
            ...r,
            status: isCompliant ? 'Warning' : 'Compliant',
            score: isCompliant ? 45 : 95
          };
        }
        return r;
      });

      const updatedCase = {
        ...currentCase,
        compliance: {
          ...data,
          requirements: updatedRequirements
        }
      };

      const response = await apiService.updateProject(currentCase._id, updatedCase);
      if (onUpdateCase) onUpdateCase(response);
      toast.success("Requirement status updated!");
    } catch (e) {
      console.error(e);
      toast.error("Failed to update requirement");
    }
  };

  const dismissAlert = async (alertId) => {
    if (!currentCase?._id) {
      toast.error("An active case is required to save updates.");
      return;
    }
    try {
      let data = currentCase.compliance || defaultCompliance;
      const updatedAlerts = data.alerts.filter(a => a.id !== alertId);

      const updatedCase = {
        ...currentCase,
        compliance: {
          ...data,
          alerts: updatedAlerts
        }
      };

      const response = await apiService.updateProject(currentCase._id, updatedCase);
      if (onUpdateCase) onUpdateCase(response);
      toast.success("Alert dismissed.");
    } catch (e) {
      console.error(e);
      toast.error("Failed to dismiss alert");
    }
  };

  if (loading || !stats) {
    return (
      <div className="flex-1 flex items-center justify-center">
        <div className="w-8 h-8 border-4 border-indigo-500 border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div className="flex-1 flex flex-col w-full h-full min-h-0 bg-slate-50 dark:bg-transparent overflow-hidden">
      {/* Header bar */}
      <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 dark:border-white/5 bg-white/80 dark:bg-[#0B1020]/80 backdrop-blur-xl shrink-0">
        <div className="flex items-center gap-3">
          <button 
            onClick={onBack} 
            className="p-2 hover:bg-slate-100 dark:hover:bg-zinc-800 rounded-full transition-colors"
          >
            <ChevronLeft size={20} className="text-slate-600 dark:text-slate-400" />
          </button>
          <div>
            <h2 className="text-lg font-black text-slate-900 dark:text-white leading-none tracking-tight">Compliance Center</h2>
            <div className="flex items-center gap-1.5 mt-1">
              <span className="w-1.5 h-1.5 rounded-full bg-indigo-500 animate-pulse" />
              <span className="text-[9px] font-black text-indigo-500 uppercase tracking-widest">ENTERPRISE AUDIT ACTIVE</span>
            </div>
          </div>
        </div>

        <button 
          onClick={handleExportReport} 
          className="flex items-center gap-1.5 px-3.5 py-2 bg-indigo-50 dark:bg-indigo-950/20 text-indigo-600 dark:text-indigo-400 border border-indigo-200/30 rounded-xl text-xs font-black uppercase tracking-wider"
        >
          <Download size={14} />
          <span>Export Report</span>
        </button>
      </div>

      {/* Main Content */}
      <div className="flex-1 overflow-y-auto px-6 py-6 custom-scrollbar min-h-0 select-text">
        <div className="max-w-4xl mx-auto space-y-6">

          {/* Score Dashboard Card */}
          <div className="bg-white dark:bg-[#1A2540] rounded-3xl p-6 shadow-sm">
            <div className="flex justify-between items-center">
              <div>
                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Overall Compliance Score</span>
                <h3 className="text-4xl font-black text-slate-950 dark:text-white mt-1">{stats.score}%</h3>
                <div className="flex items-center gap-1.5 bg-emerald-50 dark:bg-emerald-950/20 px-3 py-1 rounded-full text-[10px] font-black text-emerald-600 uppercase tracking-widest mt-3 w-fit">
                  <Shield size={12} fill="currentColor" />
                  <span>Risk Level: {stats.riskLevel}</span>
                </div>
              </div>
              
              <div className="w-16 h-16 rounded-full bg-gradient-to-br from-indigo-500 to-violet-600 flex items-center justify-center text-white shadow-lg shadow-indigo-500/20">
                <Zap size={28} fill="currentColor" />
              </div>
            </div>

            <div className="h-[1px] bg-slate-100 dark:bg-white/5 my-6" />

            <div className="grid grid-cols-2 gap-4">
              <div>
                <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest">Last Audit Date</span>
                <p className="text-xs font-bold text-slate-700 dark:text-slate-200 mt-1">{stats.lastAudit}</p>
              </div>
              <div>
                <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest">Pending Actions</span>
                <p className="text-xs font-bold text-amber-500 mt-1">{stats.pending} Alerts Unresolved</p>
              </div>
            </div>
          </div>

          {/* AI Banner Recommendation */}
          <div className="bg-indigo-50/50 dark:bg-indigo-950/10 border border-indigo-100 dark:border-indigo-900/30 rounded-2xl p-4 flex items-center gap-3">
            <ShieldCheck size={20} className="text-indigo-600 shrink-0" />
            <p className="text-xs font-semibold text-indigo-700 dark:text-indigo-400">
              <strong>AI Recommendation:</strong> Update Section 4 of your Privacy Policy to match the new Digital Personal Data Protection (DPDP) Act requirements.
            </p>
          </div>

          {/* Pending Alerts */}
          <div className="space-y-3">
            <h3 className="text-xs font-black tracking-widest text-slate-400 uppercase">PENDING ALERTS</h3>
            <div className="grid grid-cols-1 gap-4">
              {alerts.map(alert => (
                <div key={alert.id} className="bg-white dark:bg-[#1A2540] rounded-2xl p-5 shadow-sm flex items-start gap-4">
                  <div className={`p-3 rounded-xl shrink-0 ${alert.priority === 'High' ? 'bg-red-50 dark:bg-red-950/20 text-red-500' : 'bg-amber-50 dark:bg-amber-950/20 text-amber-505'}`}>
                    <AlertTriangle size={20} />
                  </div>

                  <div className="flex-1 min-w-0">
                    <div className="flex justify-between items-center">
                      <h4 className="text-sm font-black text-slate-900 dark:text-white truncate">{alert.title}</h4>
                      <span className="text-[10px] text-slate-400 font-semibold">{alert.date}</span>
                    </div>
                    <p className="text-xs text-subtext mt-1 font-semibold leading-relaxed">{alert.desc}</p>
                    
                    <div className="flex items-center gap-3 mt-3">
                      <button 
                        onClick={() => handleReviewFix(alert)}
                        className="flex items-center gap-1 text-[10px] font-black uppercase tracking-widest text-indigo-600 hover:text-indigo-700"
                      >
                        <span>Review & Fix</span>
                        <ArrowUpRight size={12} />
                      </button>
                      <button 
                        onClick={() => dismissAlert(alert.id)}
                        className="text-[10px] font-black uppercase tracking-widest text-slate-400 hover:text-red-500"
                      >
                        Dismiss
                      </button>
                    </div>
                  </div>
                </div>
              ))}
              {alerts.length === 0 && (
                <div className="text-center py-10 bg-white dark:bg-[#1A2540] rounded-2xl">
                  <CheckCircle2 size={32} className="mx-auto text-emerald-500 mb-2" />
                  <p className="text-xs font-bold text-slate-500">All alerts resolved! Excellent compliance status.</p>
                </div>
              )}
            </div>
          </div>

          {/* Requirements List Tracker */}
          <div className="space-y-3">
            <h3 className="text-xs font-black tracking-widest text-slate-400 uppercase">REQUIREMENTS CHECKLIST TRACKER</h3>
            <div className="bg-white dark:bg-[#1A2540] rounded-2xl overflow-hidden divide-y divide-slate-100 dark:divide-white/5">
              {requirements.map(req => (
                <div key={req.id} className="p-4 flex items-center justify-between">
                  <div className="flex-1 min-w-0">
                    <h4 className="text-xs font-black text-slate-800 dark:text-white truncate">{req.title}</h4>
                    <div className="flex items-center gap-1.5 mt-1.5">
                      <CheckCircle2 size={12} className={req.status === 'Compliant' ? 'text-emerald-500' : 'text-amber-500'} />
                      <span className={`text-[10px] font-bold ${req.status === 'Compliant' ? 'text-emerald-500' : 'text-amber-500'}`}>{req.status}</span>
                    </div>
                  </div>

                  <div className="flex items-center gap-4">
                    <span className={`text-sm font-black ${req.score > 90 ? 'text-emerald-500' : 'text-amber-500'}`}>{req.score}%</span>
                    <button 
                      onClick={() => toggleRequirement(req.id)}
                      className="text-[10px] font-bold bg-slate-50 hover:bg-slate-100 dark:bg-zinc-800 dark:hover:bg-zinc-700 px-3 py-1.5 rounded-lg"
                    >
                      Toggle
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>

        </div>
      </div>

      {/* Audit Action Modal */}
      {auditItem && (
        <div className="fixed inset-0 z-[120000] flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-black/60 backdrop-blur-md" onClick={() => setAuditItem(null)} />
          <div className="relative bg-white dark:bg-zinc-900 rounded-[32px] max-w-xl w-full max-h-[85%] flex flex-col overflow-hidden shadow-2xl p-6">
            <div className="flex items-center justify-between border-b border-slate-100 dark:border-white/5 pb-4 shrink-0">
              <div>
                <h3 className="text-base font-black text-slate-900 dark:text-white">AI Compliance Audit</h3>
                <p className="text-[10px] text-slate-400 font-bold uppercase tracking-wider mt-0.5">{auditItem.title}</p>
              </div>
              <button onClick={() => setAuditItem(null)} className="p-1 hover:bg-slate-100 dark:hover:bg-zinc-800 rounded-full">
                <X size={20} className="text-slate-400" />
              </button>
            </div>

            {/* Content */}
            <div className="flex-1 overflow-y-auto mt-4 custom-scrollbar select-text space-y-4">
              {isAuditing ? (
                <div className="flex flex-col items-center justify-center py-20 gap-3">
                  <div className="w-8 h-8 border-4 border-indigo-500 border-t-transparent rounded-full animate-spin" />
                  <span className="text-xs font-black text-indigo-500 animate-pulse uppercase tracking-widest">Simulating resolution wording...</span>
                </div>
              ) : (
                <div className="prose dark:prose-invert max-w-none text-xs sm:text-sm whitespace-pre-wrap select-text leading-relaxed text-slate-800 dark:text-slate-200">
                  {auditResponse}
                </div>
              )}
            </div>

            {/* Footer */}
            <div className="flex gap-3 mt-6 pt-4 border-t border-slate-100 dark:border-white/5 shrink-0">
              <button
                onClick={() => {
                  navigator.clipboard.writeText(auditResponse);
                  toast.success("Resolution roadmap copied!");
                }}
                disabled={isAuditing || !auditResponse}
                className="flex-1 py-3 bg-slate-100 dark:bg-zinc-850 hover:bg-slate-200 hover:dark:bg-zinc-800 rounded-xl font-black text-xs uppercase tracking-wider transition-all disabled:opacity-50"
              >
                Copy Actions
              </button>
              <button
                onClick={() => setAuditItem(null)}
                className="flex-1 py-3 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl font-black text-xs uppercase tracking-wider transition-all"
              >
                Done
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ComplianceCenter;
